name: classes
description: Classes created as part of Algorithmics II course
version: 1.0.0
repository: https://github.com/pete-g00/algs-ii-prep

environment:
  sdk: '>=2.17.0-69.2.beta <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.4
dependencies: 
  binary_tree: ^1.0.5
  quiver: ^3.1.0
